
# select *
# from ONLINE_SALE S
# JOIN USER_INFO I ON S.USER_ID = I.USER_ID
# WHERE I.GENDER IS NOT NULL
# AND YEAR(S.SALES_DATE) = 2022
# AND MONTH(S.SALES_DATE) = 2
# AND I.GENDER = 0

select YEAR(S.SALES_DATE) YEAR,MONTH(S.SALES_DATE) MONTH,I.GENDER, COUNT(Distinct S.USER_ID) USERS
from ONLINE_SALE S
JOIN USER_INFO I ON S.USER_ID = I.USER_ID
WHERE I.GENDER IS NOT NULL
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
order by YEAR(S.SALES_DATE),MONTH(S.SALES_DATE),I.GENDER

# select *
# from ONLINE_SALE S
# JOIN USER_INFO I ON S.USER_ID = I.USER_ID
# WHERE I.GENDER IS NOT NULL
# GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
# order by YEAR(S.SALES_DATE),MONTH(S.SALES_DATE),I.GENDER