-- 코드를 입력하세요

SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM PATIENT P 
    JOIN APPOINTMENT A ON P.PT_NO = A.PT_NO
    JOIN DOCTOR D ON D.DR_ID = A.MDDR_ID
where A.APNT_CNCL_YN = 'N'
AND A.MCDP_CD = 'CS'
AND A.APNT_YMD LIKE '2022-04-13%'
ORDER BY A.APNT_YMD ASC

# select APNT_YMD
# FROM APPOINTMENT A
# where (YEAR(A.APNT_YMD) = 2022 AND MONTH(A.APNT_YMD) = 4 AND DAY(A.APNT_YMD) = 13)
