SELECT
  EMP_NO,
  EMP_NAME,
  GRADE,
  CASE WHEN GRADE = 'S' THEN SAL * 0.2
       WHEN GRADE = 'A' THEN SAL * 0.15
       WHEN GRADE = 'B' THEN SAL * 0.1
       ELSE 0
  END AS BONUS
FROM (
  SELECT
    E.EMP_NO,
    E.EMP_NAME,
    E.SAL,
    CASE WHEN SUM(G.SCORE) / 2 >= 96 THEN 'S'
         WHEN SUM(G.SCORE) / 2 >= 90 THEN 'A'
         WHEN SUM(G.SCORE) / 2 >= 80 THEN 'B'
         ELSE 'C'
    END AS GRADE
  FROM HR_EMPLOYEES E
  JOIN HR_GRADE G ON E.EMP_NO = G.EMP_NO
  GROUP BY E.EMP_NO, E.EMP_NAME, E.SAL
) AS Calculated
ORDER BY EMP_NO;
