-- 코드를 입력하세요

select p.MEMBER_NAME, r.REVIEW_TEXT, DATE_FORMAT(r.REVIEW_DATE,'%Y-%m-%d') REVIEW_DATE
from
(SELECT MEMBER_ID, count(MEMBER_ID) count1
FROM REST_REVIEW R 
GROUP BY MEMBER_ID
order by count1 desc
limit 1) mt
left join REST_REVIEW r on mt.MEMBER_ID = r.MEMBER_ID
join MEMBER_PROFILE P ON mt.MEMBER_ID = P.MEMBER_ID
order by r.REVIEW_DATE, r.REVIEW_TEXT


# JOIN MEMBER_PROFILE P ON R.MEMBER_ID = P.MEMBER_ID

# SELECT MEMBER_ID, count(MEMBER_ID) count
# FROM REST_REVIEW R 
# join MEMBER_PROFILE P ON mt.MEMBER_ID = P.MEMBER_ID
# ORDER BY count desc, REVIEW_DATE,REVIEW_TEXT asc

# SELECT MEMBER_ID, count(MEMBER_ID) count1
# FROM REST_REVIEW R 
# GROUP BY MEMBER_ID
# order by count1 desc
# limit 1