-- 코드를 작성해주세요

# select I.ID,N.FISH_NAME, I.LENGTH
# from FISH_INFO I join FISH_NAME_INFO N
# on I.FISH_TYPE = N.FISH_TYPE
# where I.FISH_TYPE, I.LENGTH IN (select FISH_TYPE,MAX(LENGTH) LENGTH
# from FISH_INFO 
# where LENGTH IS NOT NULL
# GROUP BY FISH_TYPE)

SELECT FI.ID, N.FISH_NAME , FI.LENGTH
FROM FISH_INFO FI
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    WHERE LENGTH IS NOT NULL
    GROUP BY FISH_TYPE
) AS MaxLengths ON FI.FISH_TYPE = MaxLengths.FISH_TYPE AND FI.LENGTH = MaxLengths.MAX_LENGTH
JOIN FISH_NAME_INFO N
on FI.FISH_TYPE = N.FISH_TYPE